line-length = 100
target-version = "py39"

[lint]
select = ["F", "E", "W", "I"]
ignore = ["E203"]

[lint.per-file-ignores]
"tests/*" = ["F401", "E402"]
"tests/**" = ["E402", "E501"]  # allow import-at-top exceptions and long lines in tests
