line-length = 120
target-version = "py39"

[lint]
select = ["E", "F", "W", "I", "UP", "B"]
ignore = ["E501"]  # temporary to pass CI; follow-up PR can re-enable

[lint.per-file-ignores]
"tests/*" = ["F401", "E402"]
"tests/**" = ["E402", "E501"]  # allow import-at-top exceptions and long lines in tests
