line-length = 100
target-version = "py39"

[lint]
select = ["F", "E", "W", "I"]
ignore = ["E203"]

[lint.per-file-ignores]
"tests/*" = ["F401"]
"src/utils/ui_helpers.py" = ["F401"]  # façade only - allows unused imports
